version: '3.9'

services:
  node1:
    build: .
    container_name: node1
    command: python node.py node1 node1,node2,node3
    ports:
      - "5001:5000"
    networks:
      - kv-net

  node2:
    build: .
    container_name: node2
    command: python node.py node2 node1,node2,node3
    ports:
      - "5002:5000"
    networks:
      - kv-net

  node3:
    build: .
    container_name: node3
    command: python node.py node3 node1,node2,node3
    ports:
      - "5003:5000"
    networks:
      - kv-net

networks:
  kv-net:
    driver: bridge

